---
defaults:
  run:
    working-directory: packages/container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "npm install"
      - run: "npm run build"
      - env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        uses: chrislennon/action-aws-cli@v1.1
      - env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: "${‌{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${‌{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: "aws s3 sync dist s3://${‌{ secrets.AWS_S3_BUCKET_NAME }}/container/latest"
name: deploy-container
true:
  push:
    branches:
      - master
    paths:
      - container/**
